# Generated by Django 3.1.7 on 2021-03-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_number', models.IntegerField()),
                ('emp_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='person',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='voter',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relapp.employee'),
        ),
    ]
